//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: Message.proto
//
//package com.mine.proto;
//
//public final class IMessage {
//  private IMessage() {}
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistryLite registry) {
//  }
//
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistry registry) {
//    registerAllExtensions(
//        (com.google.protobuf.ExtensionRegistryLite) registry);
//  }
//  public interface MessageOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:proto.Message)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>required int32 type = 1;</code>
//     * @return Whether the type field is set.
//     */
//    boolean hasType();
//    /**
//     * <code>required int32 type = 1;</code>
//     * @return The type.
//     */
//    int getType();
//
//    /**
//     * <code>required string sender = 2;</code>
//     * @return Whether the sender field is set.
//     */
//    boolean hasSender();
//    /**
//     * <code>required string sender = 2;</code>
//     * @return The sender.
//     */
//    java.lang.String getSender();
//    /**
//     * <code>required string sender = 2;</code>
//     * @return The bytes for sender.
//     */
//    com.google.protobuf.ByteString
//        getSenderBytes();
//
//    /**
//     * <code>optional string receiver = 3;</code>
//     * @return Whether the receiver field is set.
//     */
//    boolean hasReceiver();
//    /**
//     * <code>optional string receiver = 3;</code>
//     * @return The receiver.
//     */
//    java.lang.String getReceiver();
//    /**
//     * <code>optional string receiver = 3;</code>
//     * @return The bytes for receiver.
//     */
//    com.google.protobuf.ByteString
//        getReceiverBytes();
//
//    /**
//     * <code>optional string msg = 4;</code>
//     * @return Whether the msg field is set.
//     */
//    boolean hasMsg();
//    /**
//     * <code>optional string msg = 4;</code>
//     * @return The msg.
//     */
//    java.lang.String getMsg();
//    /**
//     * <code>optional string msg = 4;</code>
//     * @return The bytes for msg.
//     */
//    com.google.protobuf.ByteString
//        getMsgBytes();
//
//    /**
//     * <code>optional string sessionId = 5;</code>
//     * @return Whether the sessionId field is set.
//     */
//    boolean hasSessionId();
//    /**
//     * <code>optional string sessionId = 5;</code>
//     * @return The sessionId.
//     */
//    java.lang.String getSessionId();
//    /**
//     * <code>optional string sessionId = 5;</code>
//     * @return The bytes for sessionId.
//     */
//    com.google.protobuf.ByteString
//        getSessionIdBytes();
//  }
//  /**
//   * Protobuf type {@code proto.Message}
//   */
//  public  static final class Message extends
//      com.google.protobuf.GeneratedMessageV3 implements
//      // @@protoc_insertion_point(message_implements:proto.Message)
//      MessageOrBuilder {
//  private static final long serialVersionUID = 0L;
//    // Use Message.newBuilder() to construct.
//    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
//      super(builder);
//    }
//    private Message() {
//      sender_ = "";
//      receiver_ = "";
//      msg_ = "";
//      sessionId_ = "";
//    }
//
//    @java.lang.Override
//    @SuppressWarnings({"unused"})
//    protected java.lang.Object newInstance(
//        UnusedPrivateParameter unused) {
//      return new Message();
//    }
//
//    @java.lang.Override
//    public final com.google.protobuf.UnknownFieldSet
//    getUnknownFields() {
//      return this.unknownFields;
//    }
//    private Message(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      this();
//      if (extensionRegistry == null) {
//        throw new java.lang.NullPointerException();
//      }
//      int mutable_bitField0_ = 0;
//      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
//          com.google.protobuf.UnknownFieldSet.newBuilder();
//      try {
//        boolean done = false;
//        while (!done) {
//          int tag = input.readTag();
//          switch (tag) {
//            case 0:
//              done = true;
//              break;
//            case 8: {
//              bitField0_ |= 0x00000001;
//              type_ = input.readInt32();
//              break;
//            }
//            case 18: {
//              com.google.protobuf.ByteString bs = input.readBytes();
//              bitField0_ |= 0x00000002;
//              sender_ = bs;
//              break;
//            }
//            case 26: {
//              com.google.protobuf.ByteString bs = input.readBytes();
//              bitField0_ |= 0x00000004;
//              receiver_ = bs;
//              break;
//            }
//            case 34: {
//              com.google.protobuf.ByteString bs = input.readBytes();
//              bitField0_ |= 0x00000008;
//              msg_ = bs;
//              break;
//            }
//            case 42: {
//              com.google.protobuf.ByteString bs = input.readBytes();
//              bitField0_ |= 0x00000010;
//              sessionId_ = bs;
//              break;
//            }
//            default: {
//              if (!parseUnknownField(
//                  input, unknownFields, extensionRegistry, tag)) {
//                done = true;
//              }
//              break;
//            }
//          }
//        }
//      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//        throw e.setUnfinishedMessage(this);
//      } catch (java.io.IOException e) {
//        throw new com.google.protobuf.InvalidProtocolBufferException(
//            e).setUnfinishedMessage(this);
//      } finally {
//        this.unknownFields = unknownFields.build();
//        makeExtensionsImmutable();
//      }
//    }
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return com.mine.proto.IMessage.internal_static_proto_Message_descriptor;
//    }
//
//    @java.lang.Override
//    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return com.mine.proto.IMessage.internal_static_proto_Message_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              com.mine.proto.IMessage.Message.class, com.mine.proto.IMessage.Message.Builder.class);
//    }
//
//    private int bitField0_;
//    public static final int TYPE_FIELD_NUMBER = 1;
//    private int type_;
//    /**
//     * <code>required int32 type = 1;</code>
//     * @return Whether the type field is set.
//     */
//    public boolean hasType() {
//      return ((bitField0_ & 0x00000001) != 0);
//    }
//    /**
//     * <code>required int32 type = 1;</code>
//     * @return The type.
//     */
//    public int getType() {
//      return type_;
//    }
//
//    public static final int SENDER_FIELD_NUMBER = 2;
//    private volatile java.lang.Object sender_;
//    /**
//     * <code>required string sender = 2;</code>
//     * @return Whether the sender field is set.
//     */
//    public boolean hasSender() {
//      return ((bitField0_ & 0x00000002) != 0);
//    }
//    /**
//     * <code>required string sender = 2;</code>
//     * @return The sender.
//     */
//    public java.lang.String getSender() {
//      java.lang.Object ref = sender_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        if (bs.isValidUtf8()) {
//          sender_ = s;
//        }
//        return s;
//      }
//    }
//    /**
//     * <code>required string sender = 2;</code>
//     * @return The bytes for sender.
//     */
//    public com.google.protobuf.ByteString
//        getSenderBytes() {
//      java.lang.Object ref = sender_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        sender_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int RECEIVER_FIELD_NUMBER = 3;
//    private volatile java.lang.Object receiver_;
//    /**
//     * <code>optional string receiver = 3;</code>
//     * @return Whether the receiver field is set.
//     */
//    public boolean hasReceiver() {
//      return ((bitField0_ & 0x00000004) != 0);
//    }
//    /**
//     * <code>optional string receiver = 3;</code>
//     * @return The receiver.
//     */
//    public java.lang.String getReceiver() {
//      java.lang.Object ref = receiver_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        if (bs.isValidUtf8()) {
//          receiver_ = s;
//        }
//        return s;
//      }
//    }
//    /**
//     * <code>optional string receiver = 3;</code>
//     * @return The bytes for receiver.
//     */
//    public com.google.protobuf.ByteString
//        getReceiverBytes() {
//      java.lang.Object ref = receiver_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        receiver_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int MSG_FIELD_NUMBER = 4;
//    private volatile java.lang.Object msg_;
//    /**
//     * <code>optional string msg = 4;</code>
//     * @return Whether the msg field is set.
//     */
//    public boolean hasMsg() {
//      return ((bitField0_ & 0x00000008) != 0);
//    }
//    /**
//     * <code>optional string msg = 4;</code>
//     * @return The msg.
//     */
//    public java.lang.String getMsg() {
//      java.lang.Object ref = msg_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        if (bs.isValidUtf8()) {
//          msg_ = s;
//        }
//        return s;
//      }
//    }
//    /**
//     * <code>optional string msg = 4;</code>
//     * @return The bytes for msg.
//     */
//    public com.google.protobuf.ByteString
//        getMsgBytes() {
//      java.lang.Object ref = msg_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        msg_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int SESSIONID_FIELD_NUMBER = 5;
//    private volatile java.lang.Object sessionId_;
//    /**
//     * <code>optional string sessionId = 5;</code>
//     * @return Whether the sessionId field is set.
//     */
//    public boolean hasSessionId() {
//      return ((bitField0_ & 0x00000010) != 0);
//    }
//    /**
//     * <code>optional string sessionId = 5;</code>
//     * @return The sessionId.
//     */
//    public java.lang.String getSessionId() {
//      java.lang.Object ref = sessionId_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        if (bs.isValidUtf8()) {
//          sessionId_ = s;
//        }
//        return s;
//      }
//    }
//    /**
//     * <code>optional string sessionId = 5;</code>
//     * @return The bytes for sessionId.
//     */
//    public com.google.protobuf.ByteString
//        getSessionIdBytes() {
//      java.lang.Object ref = sessionId_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        sessionId_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    private byte memoizedIsInitialized = -1;
//    @java.lang.Override
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      if (!hasType()) {
//        memoizedIsInitialized = 0;
//        return false;
//      }
//      if (!hasSender()) {
//        memoizedIsInitialized = 0;
//        return false;
//      }
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    @java.lang.Override
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      if (((bitField0_ & 0x00000001) != 0)) {
//        output.writeInt32(1, type_);
//      }
//      if (((bitField0_ & 0x00000002) != 0)) {
//        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sender_);
//      }
//      if (((bitField0_ & 0x00000004) != 0)) {
//        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, receiver_);
//      }
//      if (((bitField0_ & 0x00000008) != 0)) {
//        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, msg_);
//      }
//      if (((bitField0_ & 0x00000010) != 0)) {
//        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sessionId_);
//      }
//      unknownFields.writeTo(output);
//    }
//
//    @java.lang.Override
//    public int getSerializedSize() {
//      int size = memoizedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (((bitField0_ & 0x00000001) != 0)) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeInt32Size(1, type_);
//      }
//      if (((bitField0_ & 0x00000002) != 0)) {
//        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sender_);
//      }
//      if (((bitField0_ & 0x00000004) != 0)) {
//        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, receiver_);
//      }
//      if (((bitField0_ & 0x00000008) != 0)) {
//        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, msg_);
//      }
//      if (((bitField0_ & 0x00000010) != 0)) {
//        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, sessionId_);
//      }
//      size += unknownFields.getSerializedSize();
//      memoizedSize = size;
//      return size;
//    }
//
//    @java.lang.Override
//    public boolean equals(final java.lang.Object obj) {
//      if (obj == this) {
//       return true;
//      }
//      if (!(obj instanceof com.mine.proto.IMessage.Message)) {
//        return super.equals(obj);
//      }
//      com.mine.proto.IMessage.Message other = (com.mine.proto.IMessage.Message) obj;
//
//      if (hasType() != other.hasType()) return false;
//      if (hasType()) {
//        if (getType()
//            != other.getType()) return false;
//      }
//      if (hasSender() != other.hasSender()) return false;
//      if (hasSender()) {
//        if (!getSender()
//            .equals(other.getSender())) return false;
//      }
//      if (hasReceiver() != other.hasReceiver()) return false;
//      if (hasReceiver()) {
//        if (!getReceiver()
//            .equals(other.getReceiver())) return false;
//      }
//      if (hasMsg() != other.hasMsg()) return false;
//      if (hasMsg()) {
//        if (!getMsg()
//            .equals(other.getMsg())) return false;
//      }
//      if (hasSessionId() != other.hasSessionId()) return false;
//      if (hasSessionId()) {
//        if (!getSessionId()
//            .equals(other.getSessionId())) return false;
//      }
//      if (!unknownFields.equals(other.unknownFields)) return false;
//      return true;
//    }
//
//    @java.lang.Override
//    public int hashCode() {
//      if (memoizedHashCode != 0) {
//        return memoizedHashCode;
//      }
//      int hash = 41;
//      hash = (19 * hash) + getDescriptor().hashCode();
//      if (hasType()) {
//        hash = (37 * hash) + TYPE_FIELD_NUMBER;
//        hash = (53 * hash) + getType();
//      }
//      if (hasSender()) {
//        hash = (37 * hash) + SENDER_FIELD_NUMBER;
//        hash = (53 * hash) + getSender().hashCode();
//      }
//      if (hasReceiver()) {
//        hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
//        hash = (53 * hash) + getReceiver().hashCode();
//      }
//      if (hasMsg()) {
//        hash = (37 * hash) + MSG_FIELD_NUMBER;
//        hash = (53 * hash) + getMsg().hashCode();
//      }
//      if (hasSessionId()) {
//        hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
//        hash = (53 * hash) + getSessionId().hashCode();
//      }
//      hash = (29 * hash) + unknownFields.hashCode();
//      memoizedHashCode = hash;
//      return hash;
//    }
//
//    public static com.mine.proto.IMessage.Message parseFrom(
//        java.nio.ByteBuffer data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.mine.proto.IMessage.Message parseFrom(
//        java.nio.ByteBuffer data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.mine.proto.IMessage.Message parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.mine.proto.IMessage.Message parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.mine.proto.IMessage.Message parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.mine.proto.IMessage.Message parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.mine.proto.IMessage.Message parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static com.mine.proto.IMessage.Message parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static com.mine.proto.IMessage.Message parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input);
//    }
//    public static com.mine.proto.IMessage.Message parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static com.mine.proto.IMessage.Message parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static com.mine.proto.IMessage.Message parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    @java.lang.Override
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(com.mine.proto.IMessage.Message prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//    @java.lang.Override
//    public Builder toBuilder() {
//      return this == DEFAULT_INSTANCE
//          ? new Builder() : new Builder().mergeFrom(this);
//    }
//
//    @java.lang.Override
//    protected Builder newBuilderForType(
//        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code proto.Message}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:proto.Message)
//        com.mine.proto.IMessage.MessageOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return com.mine.proto.IMessage.internal_static_proto_Message_descriptor;
//      }
//
//      @java.lang.Override
//      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return com.mine.proto.IMessage.internal_static_proto_Message_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                com.mine.proto.IMessage.Message.class, com.mine.proto.IMessage.Message.Builder.class);
//      }
//
//      // Construct using com.mine.proto.IMessage.Message.newBuilder()
//      private Builder() {
//        maybeForceBuilderInitialization();
//      }
//
//      private Builder(
//          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//        super(parent);
//        maybeForceBuilderInitialization();
//      }
//      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessageV3
//                .alwaysUseFieldBuilders) {
//        }
//      }
//      @java.lang.Override
//      public Builder clear() {
//        super.clear();
//        type_ = 0;
//        bitField0_ = (bitField0_ & ~0x00000001);
//        sender_ = "";
//        bitField0_ = (bitField0_ & ~0x00000002);
//        receiver_ = "";
//        bitField0_ = (bitField0_ & ~0x00000004);
//        msg_ = "";
//        bitField0_ = (bitField0_ & ~0x00000008);
//        sessionId_ = "";
//        bitField0_ = (bitField0_ & ~0x00000010);
//        return this;
//      }
//
//      @java.lang.Override
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return com.mine.proto.IMessage.internal_static_proto_Message_descriptor;
//      }
//
//      @java.lang.Override
//      public com.mine.proto.IMessage.Message getDefaultInstanceForType() {
//        return com.mine.proto.IMessage.Message.getDefaultInstance();
//      }
//
//      @java.lang.Override
//      public com.mine.proto.IMessage.Message build() {
//        com.mine.proto.IMessage.Message result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      @java.lang.Override
//      public com.mine.proto.IMessage.Message buildPartial() {
//        com.mine.proto.IMessage.Message result = new com.mine.proto.IMessage.Message(this);
//        int from_bitField0_ = bitField0_;
//        int to_bitField0_ = 0;
//        if (((from_bitField0_ & 0x00000001) != 0)) {
//          result.type_ = type_;
//          to_bitField0_ |= 0x00000001;
//        }
//        if (((from_bitField0_ & 0x00000002) != 0)) {
//          to_bitField0_ |= 0x00000002;
//        }
//        result.sender_ = sender_;
//        if (((from_bitField0_ & 0x00000004) != 0)) {
//          to_bitField0_ |= 0x00000004;
//        }
//        result.receiver_ = receiver_;
//        if (((from_bitField0_ & 0x00000008) != 0)) {
//          to_bitField0_ |= 0x00000008;
//        }
//        result.msg_ = msg_;
//        if (((from_bitField0_ & 0x00000010) != 0)) {
//          to_bitField0_ |= 0x00000010;
//        }
//        result.sessionId_ = sessionId_;
//        result.bitField0_ = to_bitField0_;
//        onBuilt();
//        return result;
//      }
//
//      @java.lang.Override
//      public Builder clone() {
//        return super.clone();
//      }
//      @java.lang.Override
//      public Builder setField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          java.lang.Object value) {
//        return super.setField(field, value);
//      }
//      @java.lang.Override
//      public Builder clearField(
//          com.google.protobuf.Descriptors.FieldDescriptor field) {
//        return super.clearField(field);
//      }
//      @java.lang.Override
//      public Builder clearOneof(
//          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
//        return super.clearOneof(oneof);
//      }
//      @java.lang.Override
//      public Builder setRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          int index, java.lang.Object value) {
//        return super.setRepeatedField(field, index, value);
//      }
//      @java.lang.Override
//      public Builder addRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          java.lang.Object value) {
//        return super.addRepeatedField(field, value);
//      }
//      @java.lang.Override
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof com.mine.proto.IMessage.Message) {
//          return mergeFrom((com.mine.proto.IMessage.Message)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(com.mine.proto.IMessage.Message other) {
//        if (other == com.mine.proto.IMessage.Message.getDefaultInstance()) return this;
//        if (other.hasType()) {
//          setType(other.getType());
//        }
//        if (other.hasSender()) {
//          bitField0_ |= 0x00000002;
//          sender_ = other.sender_;
//          onChanged();
//        }
//        if (other.hasReceiver()) {
//          bitField0_ |= 0x00000004;
//          receiver_ = other.receiver_;
//          onChanged();
//        }
//        if (other.hasMsg()) {
//          bitField0_ |= 0x00000008;
//          msg_ = other.msg_;
//          onChanged();
//        }
//        if (other.hasSessionId()) {
//          bitField0_ |= 0x00000010;
//          sessionId_ = other.sessionId_;
//          onChanged();
//        }
//        this.mergeUnknownFields(other.unknownFields);
//        onChanged();
//        return this;
//      }
//
//      @java.lang.Override
//      public final boolean isInitialized() {
//        if (!hasType()) {
//          return false;
//        }
//        if (!hasSender()) {
//          return false;
//        }
//        return true;
//      }
//
//      @java.lang.Override
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        com.mine.proto.IMessage.Message parsedMessage = null;
//        try {
//          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          parsedMessage = (com.mine.proto.IMessage.Message) e.getUnfinishedMessage();
//          throw e.unwrapIOException();
//        } finally {
//          if (parsedMessage != null) {
//            mergeFrom(parsedMessage);
//          }
//        }
//        return this;
//      }
//      private int bitField0_;
//
//      private int type_ ;
//      /**
//       * <code>required int32 type = 1;</code>
//       * @return Whether the type field is set.
//       */
//      public boolean hasType() {
//        return ((bitField0_ & 0x00000001) != 0);
//      }
//      /**
//       * <code>required int32 type = 1;</code>
//       * @return The type.
//       */
//      public int getType() {
//        return type_;
//      }
//      /**
//       * <code>required int32 type = 1;</code>
//       * @param value The type to set.
//       * @return This builder for chaining.
//       */
//      public Builder setType(int value) {
//        bitField0_ |= 0x00000001;
//        type_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>required int32 type = 1;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearType() {
//        bitField0_ = (bitField0_ & ~0x00000001);
//        type_ = 0;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object sender_ = "";
//      /**
//       * <code>required string sender = 2;</code>
//       * @return Whether the sender field is set.
//       */
//      public boolean hasSender() {
//        return ((bitField0_ & 0x00000002) != 0);
//      }
//      /**
//       * <code>required string sender = 2;</code>
//       * @return The sender.
//       */
//      public java.lang.String getSender() {
//        java.lang.Object ref = sender_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          if (bs.isValidUtf8()) {
//            sender_ = s;
//          }
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>required string sender = 2;</code>
//       * @return The bytes for sender.
//       */
//      public com.google.protobuf.ByteString
//          getSenderBytes() {
//        java.lang.Object ref = sender_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          sender_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>required string sender = 2;</code>
//       * @param value The sender to set.
//       * @return This builder for chaining.
//       */
//      public Builder setSender(
//          java.lang.String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000002;
//        sender_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>required string sender = 2;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearSender() {
//        bitField0_ = (bitField0_ & ~0x00000002);
//        sender_ = getDefaultInstance().getSender();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>required string sender = 2;</code>
//       * @param value The bytes for sender to set.
//       * @return This builder for chaining.
//       */
//      public Builder setSenderBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000002;
//        sender_ = value;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object receiver_ = "";
//      /**
//       * <code>optional string receiver = 3;</code>
//       * @return Whether the receiver field is set.
//       */
//      public boolean hasReceiver() {
//        return ((bitField0_ & 0x00000004) != 0);
//      }
//      /**
//       * <code>optional string receiver = 3;</code>
//       * @return The receiver.
//       */
//      public java.lang.String getReceiver() {
//        java.lang.Object ref = receiver_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          if (bs.isValidUtf8()) {
//            receiver_ = s;
//          }
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>optional string receiver = 3;</code>
//       * @return The bytes for receiver.
//       */
//      public com.google.protobuf.ByteString
//          getReceiverBytes() {
//        java.lang.Object ref = receiver_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          receiver_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>optional string receiver = 3;</code>
//       * @param value The receiver to set.
//       * @return This builder for chaining.
//       */
//      public Builder setReceiver(
//          java.lang.String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000004;
//        receiver_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string receiver = 3;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearReceiver() {
//        bitField0_ = (bitField0_ & ~0x00000004);
//        receiver_ = getDefaultInstance().getReceiver();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string receiver = 3;</code>
//       * @param value The bytes for receiver to set.
//       * @return This builder for chaining.
//       */
//      public Builder setReceiverBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000004;
//        receiver_ = value;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object msg_ = "";
//      /**
//       * <code>optional string msg = 4;</code>
//       * @return Whether the msg field is set.
//       */
//      public boolean hasMsg() {
//        return ((bitField0_ & 0x00000008) != 0);
//      }
//      /**
//       * <code>optional string msg = 4;</code>
//       * @return The msg.
//       */
//      public java.lang.String getMsg() {
//        java.lang.Object ref = msg_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          if (bs.isValidUtf8()) {
//            msg_ = s;
//          }
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>optional string msg = 4;</code>
//       * @return The bytes for msg.
//       */
//      public com.google.protobuf.ByteString
//          getMsgBytes() {
//        java.lang.Object ref = msg_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          msg_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>optional string msg = 4;</code>
//       * @param value The msg to set.
//       * @return This builder for chaining.
//       */
//      public Builder setMsg(
//          java.lang.String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000008;
//        msg_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string msg = 4;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearMsg() {
//        bitField0_ = (bitField0_ & ~0x00000008);
//        msg_ = getDefaultInstance().getMsg();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string msg = 4;</code>
//       * @param value The bytes for msg to set.
//       * @return This builder for chaining.
//       */
//      public Builder setMsgBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000008;
//        msg_ = value;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object sessionId_ = "";
//      /**
//       * <code>optional string sessionId = 5;</code>
//       * @return Whether the sessionId field is set.
//       */
//      public boolean hasSessionId() {
//        return ((bitField0_ & 0x00000010) != 0);
//      }
//      /**
//       * <code>optional string sessionId = 5;</code>
//       * @return The sessionId.
//       */
//      public java.lang.String getSessionId() {
//        java.lang.Object ref = sessionId_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          if (bs.isValidUtf8()) {
//            sessionId_ = s;
//          }
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>optional string sessionId = 5;</code>
//       * @return The bytes for sessionId.
//       */
//      public com.google.protobuf.ByteString
//          getSessionIdBytes() {
//        java.lang.Object ref = sessionId_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          sessionId_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>optional string sessionId = 5;</code>
//       * @param value The sessionId to set.
//       * @return This builder for chaining.
//       */
//      public Builder setSessionId(
//          java.lang.String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000010;
//        sessionId_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string sessionId = 5;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearSessionId() {
//        bitField0_ = (bitField0_ & ~0x00000010);
//        sessionId_ = getDefaultInstance().getSessionId();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string sessionId = 5;</code>
//       * @param value The bytes for sessionId to set.
//       * @return This builder for chaining.
//       */
//      public Builder setSessionIdBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000010;
//        sessionId_ = value;
//        onChanged();
//        return this;
//      }
//      @java.lang.Override
//      public final Builder setUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.setUnknownFields(unknownFields);
//      }
//
//      @java.lang.Override
//      public final Builder mergeUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.mergeUnknownFields(unknownFields);
//      }
//
//
//      // @@protoc_insertion_point(builder_scope:proto.Message)
//    }
//
//    // @@protoc_insertion_point(class_scope:proto.Message)
//    private static final com.mine.proto.IMessage.Message DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new com.mine.proto.IMessage.Message();
//    }
//
//    public static com.mine.proto.IMessage.Message getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
//        PARSER = new com.google.protobuf.AbstractParser<Message>() {
//      @java.lang.Override
//      public Message parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return new Message(input, extensionRegistry);
//      }
//    };
//
//    public static com.google.protobuf.Parser<Message> parser() {
//      return PARSER;
//    }
//
//    @java.lang.Override
//    public com.google.protobuf.Parser<Message> getParserForType() {
//      return PARSER;
//    }
//
//    @java.lang.Override
//    public com.mine.proto.IMessage.Message getDefaultInstanceForType() {
//      return DEFAULT_INSTANCE;
//    }
//
//  }
//
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_proto_Message_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//      internal_static_proto_Message_fieldAccessorTable;
//
//  public static com.google.protobuf.Descriptors.FileDescriptor
//      getDescriptor() {
//    return descriptor;
//  }
//  private static  com.google.protobuf.Descriptors.FileDescriptor
//      descriptor;
//  static {
//    java.lang.String[] descriptorData = {
//      "\n\rMessage.proto\022\005proto\"Y\n\007Message\022\014\n\004typ" +
//      "e\030\001 \002(\005\022\016\n\006sender\030\002 \002(\t\022\020\n\010receiver\030\003 \001(" +
//      "\t\022\013\n\003msg\030\004 \001(\t\022\021\n\tsessionId\030\005 \001(\tB\032\n\016com" +
//      ".mine.protoB\010IMessage"
//    };
//    descriptor = com.google.protobuf.Descriptors.FileDescriptor
//      .internalBuildGeneratedFileFrom(descriptorData,
//        new com.google.protobuf.Descriptors.FileDescriptor[] {
//        });
//    internal_static_proto_Message_descriptor =
//      getDescriptor().getMessageTypes().get(0);
//    internal_static_proto_Message_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//        internal_static_proto_Message_descriptor,
//        new java.lang.String[] { "Type", "Sender", "Receiver", "Msg", "SessionId", });
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
//}
